[2021-08-31 12:25:07,162] {processor.py:162} INFO - Started process (PID=1322) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:25:07,163] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:25:07,163] {logging_mixin.py:109} INFO - [2021-08-31 12:25:07,163] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:25:08,354] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:25:09,274] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:25:11,506] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/azure/cosmos/session.py:186 SyntaxWarning: "is not" with a literal. Did you mean "!="?
[2021-08-31 12:25:11,558] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/azure/storage/common/_connection.py:82 SyntaxWarning: "is" with a literal. Did you mean "=="?
[2021-08-31 12:25:12,261] {logging_mixin.py:109} INFO - [2021-08-31 12:25:12,261] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:25:12,268] {logging_mixin.py:109} INFO - [2021-08-31 12:25:12,268] {dag.py:1852} INFO - Creating ORM DAG for covid_data_s3_to_snowflake
[2021-08-31 12:25:12,276] {logging_mixin.py:109} INFO - [2021-08-31 12:25:12,276] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:25:12,285] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 5.127 seconds
[2021-08-31 12:25:42,388] {processor.py:162} INFO - Started process (PID=1438) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:25:42,389] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:25:42,390] {logging_mixin.py:109} INFO - [2021-08-31 12:25:42,390] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:25:43,277] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:25:44,048] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:25:44,073] {logging_mixin.py:109} INFO - [2021-08-31 12:25:44,073] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:25:44,097] {logging_mixin.py:109} INFO - [2021-08-31 12:25:44,097] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:25:44,108] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.724 seconds
[2021-08-31 12:26:14,526] {processor.py:162} INFO - Started process (PID=1555) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:26:14,527] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:26:14,528] {logging_mixin.py:109} INFO - [2021-08-31 12:26:14,528] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:26:15,506] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:26:16,254] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:26:16,276] {logging_mixin.py:109} INFO - [2021-08-31 12:26:16,276] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:26:16,297] {logging_mixin.py:109} INFO - [2021-08-31 12:26:16,297] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:26:16,308] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.786 seconds
[2021-08-31 12:26:33,381] {processor.py:162} INFO - Started process (PID=1655) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:26:33,382] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:26:33,383] {logging_mixin.py:109} INFO - [2021-08-31 12:26:33,383] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:26:34,449] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:26:35,284] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:26:35,309] {logging_mixin.py:109} INFO - [2021-08-31 12:26:35,309] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:26:35,329] {logging_mixin.py:109} INFO - [2021-08-31 12:26:35,328] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:26:35,345] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.966 seconds
[2021-08-31 12:26:43,400] {processor.py:162} INFO - Started process (PID=1709) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:26:43,402] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:26:43,402] {logging_mixin.py:109} INFO - [2021-08-31 12:26:43,402] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:26:44,419] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:26:45,238] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:26:45,261] {logging_mixin.py:109} INFO - [2021-08-31 12:26:45,260] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:26:45,276] {logging_mixin.py:109} INFO - [2021-08-31 12:26:45,276] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:26:45,290] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.893 seconds
[2021-08-31 12:27:15,560] {processor.py:162} INFO - Started process (PID=1826) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:27:15,561] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:27:15,562] {logging_mixin.py:109} INFO - [2021-08-31 12:27:15,562] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:27:17,006] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:27:17,749] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:27:17,774] {logging_mixin.py:109} INFO - [2021-08-31 12:27:17,774] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:27:17,791] {logging_mixin.py:109} INFO - [2021-08-31 12:27:17,791] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:27:17,805] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.248 seconds
[2021-08-31 12:27:47,917] {processor.py:162} INFO - Started process (PID=1935) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:27:47,919] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:27:47,920] {logging_mixin.py:109} INFO - [2021-08-31 12:27:47,920] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:27:48,925] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:27:49,921] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:27:49,957] {logging_mixin.py:109} INFO - [2021-08-31 12:27:49,956] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:27:49,983] {logging_mixin.py:109} INFO - [2021-08-31 12:27:49,983] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:27:49,998] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.085 seconds
[2021-08-31 12:28:20,105] {processor.py:162} INFO - Started process (PID=2051) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:28:20,107] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:28:20,108] {logging_mixin.py:109} INFO - [2021-08-31 12:28:20,108] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:28:21,272] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:28:22,309] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:28:22,336] {logging_mixin.py:109} INFO - [2021-08-31 12:28:22,336] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:28:22,363] {logging_mixin.py:109} INFO - [2021-08-31 12:28:22,363] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:28:22,374] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.276 seconds
[2021-08-31 12:28:52,481] {processor.py:162} INFO - Started process (PID=2169) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:28:52,483] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:28:52,483] {logging_mixin.py:109} INFO - [2021-08-31 12:28:52,483] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:28:53,710] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:28:54,741] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:28:54,770] {logging_mixin.py:109} INFO - [2021-08-31 12:28:54,769] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:28:54,799] {logging_mixin.py:109} INFO - [2021-08-31 12:28:54,799] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:28:54,814] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.337 seconds
[2021-08-31 12:29:24,931] {processor.py:162} INFO - Started process (PID=2278) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:29:24,933] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:29:24,934] {logging_mixin.py:109} INFO - [2021-08-31 12:29:24,934] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:29:26,026] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:29:27,028] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:29:27,059] {logging_mixin.py:109} INFO - [2021-08-31 12:29:27,059] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:29:27,082] {logging_mixin.py:109} INFO - [2021-08-31 12:29:27,082] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:29:27,096] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.169 seconds
[2021-08-31 12:29:57,205] {processor.py:162} INFO - Started process (PID=2394) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:29:57,207] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:29:57,208] {logging_mixin.py:109} INFO - [2021-08-31 12:29:57,208] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:29:58,206] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:29:58,950] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:29:58,974] {logging_mixin.py:109} INFO - [2021-08-31 12:29:58,973] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:29:58,994] {logging_mixin.py:109} INFO - [2021-08-31 12:29:58,994] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:29:59,008] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.806 seconds
[2021-08-31 12:30:21,900] {processor.py:162} INFO - Started process (PID=2502) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:30:21,901] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:30:21,902] {logging_mixin.py:109} INFO - [2021-08-31 12:30:21,902] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:30:23,008] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:30:23,918] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:30:23,943] {logging_mixin.py:109} INFO - [2021-08-31 12:30:23,943] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:30:23,962] {logging_mixin.py:109} INFO - [2021-08-31 12:30:23,962] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:30:23,978] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.082 seconds
[2021-08-31 12:30:51,753] {processor.py:162} INFO - Started process (PID=2618) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:30:51,754] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:30:51,755] {logging_mixin.py:109} INFO - [2021-08-31 12:30:51,755] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:30:52,724] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:30:53,587] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:30:53,610] {logging_mixin.py:109} INFO - [2021-08-31 12:30:53,609] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:30:53,630] {logging_mixin.py:109} INFO - [2021-08-31 12:30:53,629] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:30:53,641] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.892 seconds
[2021-08-31 12:31:23,746] {processor.py:162} INFO - Started process (PID=2734) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:31:23,747] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:31:23,748] {logging_mixin.py:109} INFO - [2021-08-31 12:31:23,748] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:31:24,797] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:31:25,763] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:31:25,785] {logging_mixin.py:109} INFO - [2021-08-31 12:31:25,784] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:31:25,804] {logging_mixin.py:109} INFO - [2021-08-31 12:31:25,804] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:31:25,813] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.070 seconds
[2021-08-31 12:31:55,945] {processor.py:162} INFO - Started process (PID=2842) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:31:55,947] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:31:55,948] {logging_mixin.py:109} INFO - [2021-08-31 12:31:55,947] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:31:56,817] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:31:57,702] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:31:57,726] {logging_mixin.py:109} INFO - [2021-08-31 12:31:57,725] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:31:57,742] {logging_mixin.py:109} INFO - [2021-08-31 12:31:57,742] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:31:57,755] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.814 seconds
[2021-08-31 12:32:27,839] {processor.py:162} INFO - Started process (PID=2958) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:32:27,840] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:32:27,841] {logging_mixin.py:109} INFO - [2021-08-31 12:32:27,841] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:32:28,950] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:32:29,958] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:32:29,990] {logging_mixin.py:109} INFO - [2021-08-31 12:32:29,990] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:32:30,010] {logging_mixin.py:109} INFO - [2021-08-31 12:32:30,010] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:32:30,020] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.185 seconds
[2021-08-31 12:33:00,123] {processor.py:162} INFO - Started process (PID=3074) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:33:00,126] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:33:00,127] {logging_mixin.py:109} INFO - [2021-08-31 12:33:00,127] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:33:01,508] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:33:02,285] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:33:02,312] {logging_mixin.py:109} INFO - [2021-08-31 12:33:02,312] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:33:02,330] {logging_mixin.py:109} INFO - [2021-08-31 12:33:02,330] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:33:02,343] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.224 seconds
[2021-08-31 12:33:32,443] {processor.py:162} INFO - Started process (PID=3182) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:33:32,445] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:33:32,445] {logging_mixin.py:109} INFO - [2021-08-31 12:33:32,445] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:33:33,534] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:33:34,440] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:33:34,461] {logging_mixin.py:109} INFO - [2021-08-31 12:33:34,460] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:33:34,483] {logging_mixin.py:109} INFO - [2021-08-31 12:33:34,483] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:33:34,496] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.056 seconds
[2021-08-31 12:34:04,586] {processor.py:162} INFO - Started process (PID=3298) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:34:04,588] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:34:04,589] {logging_mixin.py:109} INFO - [2021-08-31 12:34:04,588] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:34:05,479] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:34:06,307] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:34:06,329] {logging_mixin.py:109} INFO - [2021-08-31 12:34:06,329] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:34:06,344] {logging_mixin.py:109} INFO - [2021-08-31 12:34:06,344] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:34:06,357] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.774 seconds
[2021-08-31 12:34:36,461] {processor.py:162} INFO - Started process (PID=3414) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:34:36,462] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:34:36,463] {logging_mixin.py:109} INFO - [2021-08-31 12:34:36,463] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:34:37,381] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:34:38,399] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:34:38,424] {logging_mixin.py:109} INFO - [2021-08-31 12:34:38,424] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:34:38,443] {logging_mixin.py:109} INFO - [2021-08-31 12:34:38,443] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:34:38,452] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.995 seconds
[2021-08-31 12:35:08,605] {processor.py:162} INFO - Started process (PID=3522) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:35:08,606] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:35:08,607] {logging_mixin.py:109} INFO - [2021-08-31 12:35:08,607] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:35:09,634] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:35:10,512] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:35:10,538] {logging_mixin.py:109} INFO - [2021-08-31 12:35:10,537] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:35:10,557] {logging_mixin.py:109} INFO - [2021-08-31 12:35:10,557] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:35:10,570] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.969 seconds
[2021-08-31 12:35:40,601] {processor.py:162} INFO - Started process (PID=3639) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:35:40,603] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:35:40,604] {logging_mixin.py:109} INFO - [2021-08-31 12:35:40,603] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:35:41,600] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:35:42,518] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:35:42,542] {logging_mixin.py:109} INFO - [2021-08-31 12:35:42,541] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:35:42,561] {logging_mixin.py:109} INFO - [2021-08-31 12:35:42,561] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:35:42,575] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.978 seconds
[2021-08-31 12:36:12,614] {processor.py:162} INFO - Started process (PID=3755) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:36:12,616] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:36:12,617] {logging_mixin.py:109} INFO - [2021-08-31 12:36:12,617] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:36:13,603] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:36:14,505] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:36:14,532] {logging_mixin.py:109} INFO - [2021-08-31 12:36:14,531] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:36:14,555] {logging_mixin.py:109} INFO - [2021-08-31 12:36:14,554] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:36:14,570] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.961 seconds
[2021-08-31 12:36:44,687] {processor.py:162} INFO - Started process (PID=3871) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:36:44,688] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:36:44,689] {logging_mixin.py:109} INFO - [2021-08-31 12:36:44,689] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:36:45,591] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:36:46,465] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:36:46,490] {logging_mixin.py:109} INFO - [2021-08-31 12:36:46,490] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:36:46,507] {logging_mixin.py:109} INFO - [2021-08-31 12:36:46,507] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:36:46,520] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.837 seconds
[2021-08-31 12:37:16,632] {processor.py:162} INFO - Started process (PID=3979) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:37:16,634] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:37:16,635] {logging_mixin.py:109} INFO - [2021-08-31 12:37:16,634] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:37:17,693] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:37:18,714] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:37:18,737] {logging_mixin.py:109} INFO - [2021-08-31 12:37:18,736] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:37:18,757] {logging_mixin.py:109} INFO - [2021-08-31 12:37:18,757] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:37:18,770] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.142 seconds
[2021-08-31 12:37:48,868] {processor.py:162} INFO - Started process (PID=4095) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:37:48,871] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:37:48,872] {logging_mixin.py:109} INFO - [2021-08-31 12:37:48,872] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:37:49,821] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:37:50,642] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:37:50,671] {logging_mixin.py:109} INFO - [2021-08-31 12:37:50,670] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:37:50,693] {logging_mixin.py:109} INFO - [2021-08-31 12:37:50,693] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:37:50,708] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.844 seconds
[2021-08-31 12:38:20,851] {processor.py:162} INFO - Started process (PID=4211) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:38:20,852] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:38:20,853] {logging_mixin.py:109} INFO - [2021-08-31 12:38:20,853] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:38:21,874] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:38:22,694] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:38:22,722] {logging_mixin.py:109} INFO - [2021-08-31 12:38:22,722] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:38:22,744] {logging_mixin.py:109} INFO - [2021-08-31 12:38:22,744] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:38:22,754] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.907 seconds
[2021-08-31 12:38:52,847] {processor.py:162} INFO - Started process (PID=4320) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:38:52,849] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:38:52,850] {logging_mixin.py:109} INFO - [2021-08-31 12:38:52,850] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:38:53,834] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:38:54,703] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:38:54,738] {logging_mixin.py:109} INFO - [2021-08-31 12:38:54,737] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:38:54,763] {logging_mixin.py:109} INFO - [2021-08-31 12:38:54,763] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:38:54,772] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.929 seconds
[2021-08-31 12:39:24,880] {processor.py:162} INFO - Started process (PID=4436) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:39:24,882] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:39:24,884] {logging_mixin.py:109} INFO - [2021-08-31 12:39:24,883] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:39:25,883] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:39:26,796] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:39:26,824] {logging_mixin.py:109} INFO - [2021-08-31 12:39:26,823] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:39:26,845] {logging_mixin.py:109} INFO - [2021-08-31 12:39:26,845] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:39:26,860] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.983 seconds
[2021-08-31 12:39:57,268] {processor.py:162} INFO - Started process (PID=4598) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:39:57,269] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:39:57,270] {logging_mixin.py:109} INFO - [2021-08-31 12:39:57,270] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:39:58,252] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:39:59,239] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:39:59,263] {logging_mixin.py:109} INFO - [2021-08-31 12:39:59,262] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:39:59,280] {logging_mixin.py:109} INFO - [2021-08-31 12:39:59,280] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:39:59,289] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.025 seconds
[2021-08-31 12:40:29,413] {processor.py:162} INFO - Started process (PID=4714) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:40:29,414] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:40:29,415] {logging_mixin.py:109} INFO - [2021-08-31 12:40:29,415] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:40:30,537] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:40:31,461] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:40:31,488] {logging_mixin.py:109} INFO - [2021-08-31 12:40:31,488] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:40:31,508] {logging_mixin.py:109} INFO - [2021-08-31 12:40:31,508] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:40:31,523] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.114 seconds
[2021-08-31 12:41:01,624] {processor.py:162} INFO - Started process (PID=4822) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:41:01,625] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:41:01,626] {logging_mixin.py:109} INFO - [2021-08-31 12:41:01,626] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:41:02,661] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:41:03,461] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:41:03,490] {logging_mixin.py:109} INFO - [2021-08-31 12:41:03,489] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:41:03,516] {logging_mixin.py:109} INFO - [2021-08-31 12:41:03,516] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:41:03,527] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.907 seconds
[2021-08-31 12:41:34,334] {processor.py:162} INFO - Started process (PID=4938) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:41:34,335] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:41:34,336] {logging_mixin.py:109} INFO - [2021-08-31 12:41:34,336] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:41:35,393] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:41:36,242] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:41:36,268] {logging_mixin.py:109} INFO - [2021-08-31 12:41:36,268] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:41:36,286] {logging_mixin.py:109} INFO - [2021-08-31 12:41:36,286] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:41:36,299] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.969 seconds
[2021-08-31 12:42:06,431] {processor.py:162} INFO - Started process (PID=5100) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:42:06,433] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:42:06,433] {logging_mixin.py:109} INFO - [2021-08-31 12:42:06,433] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:42:07,396] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:42:08,308] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:42:08,335] {logging_mixin.py:109} INFO - [2021-08-31 12:42:08,334] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:42:08,360] {logging_mixin.py:109} INFO - [2021-08-31 12:42:08,360] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:42:08,376] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.948 seconds
[2021-08-31 12:42:38,438] {processor.py:162} INFO - Started process (PID=5209) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:42:38,441] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:42:38,443] {logging_mixin.py:109} INFO - [2021-08-31 12:42:38,443] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:42:39,330] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:42:40,176] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:42:40,201] {logging_mixin.py:109} INFO - [2021-08-31 12:42:40,200] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:42:40,219] {logging_mixin.py:109} INFO - [2021-08-31 12:42:40,218] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:42:40,234] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.800 seconds
[2021-08-31 12:43:10,333] {processor.py:162} INFO - Started process (PID=5325) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:43:10,335] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:43:10,336] {logging_mixin.py:109} INFO - [2021-08-31 12:43:10,336] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:43:11,641] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:43:12,470] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:43:12,493] {logging_mixin.py:109} INFO - [2021-08-31 12:43:12,493] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:43:12,510] {logging_mixin.py:109} INFO - [2021-08-31 12:43:12,510] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:43:12,519] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.189 seconds
[2021-08-31 12:43:43,481] {processor.py:162} INFO - Started process (PID=5441) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:43:43,483] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:43:43,483] {logging_mixin.py:109} INFO - [2021-08-31 12:43:43,483] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:43:44,394] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:43:45,305] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:43:45,342] {logging_mixin.py:109} INFO - [2021-08-31 12:43:45,341] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:43:45,371] {logging_mixin.py:109} INFO - [2021-08-31 12:43:45,371] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:43:45,388] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.910 seconds
[2021-08-31 12:44:15,632] {processor.py:162} INFO - Started process (PID=5558) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:44:15,633] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:44:15,633] {logging_mixin.py:109} INFO - [2021-08-31 12:44:15,633] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:44:16,722] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:44:17,443] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:44:17,470] {logging_mixin.py:109} INFO - [2021-08-31 12:44:17,470] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:44:17,488] {logging_mixin.py:109} INFO - [2021-08-31 12:44:17,488] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:44:17,496] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.868 seconds
[2021-08-31 12:44:47,586] {processor.py:162} INFO - Started process (PID=5667) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:44:47,588] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:44:47,589] {logging_mixin.py:109} INFO - [2021-08-31 12:44:47,589] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:44:48,488] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:44:49,230] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:44:49,253] {logging_mixin.py:109} INFO - [2021-08-31 12:44:49,253] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:44:49,269] {logging_mixin.py:109} INFO - [2021-08-31 12:44:49,269] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:44:49,283] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.701 seconds
[2021-08-31 12:45:19,413] {processor.py:162} INFO - Started process (PID=5783) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:45:19,414] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:45:19,415] {logging_mixin.py:109} INFO - [2021-08-31 12:45:19,415] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:45:20,539] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:45:21,338] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:45:21,361] {logging_mixin.py:109} INFO - [2021-08-31 12:45:21,361] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:45:21,380] {logging_mixin.py:109} INFO - [2021-08-31 12:45:21,380] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:45:21,394] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.984 seconds
[2021-08-31 12:45:51,791] {processor.py:162} INFO - Started process (PID=5901) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:45:51,792] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:45:51,793] {logging_mixin.py:109} INFO - [2021-08-31 12:45:51,792] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:45:52,860] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:45:53,898] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:45:53,927] {logging_mixin.py:109} INFO - [2021-08-31 12:45:53,927] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:45:53,966] {logging_mixin.py:109} INFO - [2021-08-31 12:45:53,966] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:45:53,981] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.195 seconds
[2021-08-31 12:46:24,080] {processor.py:162} INFO - Started process (PID=6017) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:46:24,081] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:46:24,082] {logging_mixin.py:109} INFO - [2021-08-31 12:46:24,082] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:46:25,104] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:46:25,875] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:46:25,901] {logging_mixin.py:109} INFO - [2021-08-31 12:46:25,900] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:46:25,918] {logging_mixin.py:109} INFO - [2021-08-31 12:46:25,918] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:46:25,933] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.857 seconds
[2021-08-31 12:46:56,035] {processor.py:162} INFO - Started process (PID=6125) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:46:56,036] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:46:56,039] {logging_mixin.py:109} INFO - [2021-08-31 12:46:56,038] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:46:57,263] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:46:58,188] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:46:58,217] {logging_mixin.py:109} INFO - [2021-08-31 12:46:58,217] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:46:58,246] {logging_mixin.py:109} INFO - [2021-08-31 12:46:58,246] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:46:58,262] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.230 seconds
[2021-08-31 12:47:28,366] {processor.py:162} INFO - Started process (PID=6241) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:47:28,367] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:47:28,368] {logging_mixin.py:109} INFO - [2021-08-31 12:47:28,368] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:47:29,468] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:47:30,350] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:47:30,402] {logging_mixin.py:109} INFO - [2021-08-31 12:47:30,402] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:47:30,431] {logging_mixin.py:109} INFO - [2021-08-31 12:47:30,431] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:47:30,442] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.080 seconds
[2021-08-31 12:48:00,527] {processor.py:162} INFO - Started process (PID=6358) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:48:00,529] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:48:00,530] {logging_mixin.py:109} INFO - [2021-08-31 12:48:00,530] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:48:01,592] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:48:02,530] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:48:02,561] {logging_mixin.py:109} INFO - [2021-08-31 12:48:02,560] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:48:02,585] {logging_mixin.py:109} INFO - [2021-08-31 12:48:02,584] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:48:02,598] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.074 seconds
[2021-08-31 12:48:32,690] {processor.py:162} INFO - Started process (PID=6467) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:48:32,692] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:48:32,693] {logging_mixin.py:109} INFO - [2021-08-31 12:48:32,693] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:48:33,708] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:48:34,539] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:48:34,571] {logging_mixin.py:109} INFO - [2021-08-31 12:48:34,570] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:48:34,599] {logging_mixin.py:109} INFO - [2021-08-31 12:48:34,599] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:48:34,618] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.932 seconds
[2021-08-31 12:49:04,720] {processor.py:162} INFO - Started process (PID=6583) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:49:04,721] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:49:04,723] {logging_mixin.py:109} INFO - [2021-08-31 12:49:04,722] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:49:05,817] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:49:06,716] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:49:06,744] {logging_mixin.py:109} INFO - [2021-08-31 12:49:06,744] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:49:06,769] {logging_mixin.py:109} INFO - [2021-08-31 12:49:06,769] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:49:06,783] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.067 seconds
[2021-08-31 12:49:36,834] {processor.py:162} INFO - Started process (PID=6700) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:49:36,835] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:49:36,836] {logging_mixin.py:109} INFO - [2021-08-31 12:49:36,835] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:49:37,847] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:49:38,741] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:49:38,766] {logging_mixin.py:109} INFO - [2021-08-31 12:49:38,765] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:49:38,785] {logging_mixin.py:109} INFO - [2021-08-31 12:49:38,785] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:49:38,795] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.965 seconds
[2021-08-31 12:50:08,947] {processor.py:162} INFO - Started process (PID=6807) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:50:08,948] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:50:08,949] {logging_mixin.py:109} INFO - [2021-08-31 12:50:08,949] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:50:09,996] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:50:10,896] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:50:10,924] {logging_mixin.py:109} INFO - [2021-08-31 12:50:10,924] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:50:10,952] {logging_mixin.py:109} INFO - [2021-08-31 12:50:10,952] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:50:10,960] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.016 seconds
[2021-08-31 12:50:41,068] {processor.py:162} INFO - Started process (PID=6922) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:50:41,069] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:50:41,071] {logging_mixin.py:109} INFO - [2021-08-31 12:50:41,070] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:50:41,958] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:50:42,813] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:50:42,844] {logging_mixin.py:109} INFO - [2021-08-31 12:50:42,843] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:50:42,868] {logging_mixin.py:109} INFO - [2021-08-31 12:50:42,867] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:50:42,877] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.814 seconds
[2021-08-31 12:51:12,983] {processor.py:162} INFO - Started process (PID=7040) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:51:12,985] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:51:12,986] {logging_mixin.py:109} INFO - [2021-08-31 12:51:12,985] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:51:13,967] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:51:14,838] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:51:14,867] {logging_mixin.py:109} INFO - [2021-08-31 12:51:14,867] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:51:14,887] {logging_mixin.py:109} INFO - [2021-08-31 12:51:14,887] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:51:14,897] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.919 seconds
[2021-08-31 12:51:45,014] {processor.py:162} INFO - Started process (PID=7156) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:51:45,016] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:51:45,017] {logging_mixin.py:109} INFO - [2021-08-31 12:51:45,017] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:51:46,004] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:51:46,909] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:51:46,937] {logging_mixin.py:109} INFO - [2021-08-31 12:51:46,936] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:51:46,952] {logging_mixin.py:109} INFO - [2021-08-31 12:51:46,952] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:51:46,966] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.957 seconds
[2021-08-31 12:52:17,097] {processor.py:162} INFO - Started process (PID=7264) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:52:17,098] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:52:17,099] {logging_mixin.py:109} INFO - [2021-08-31 12:52:17,099] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:52:18,255] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:52:19,077] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:52:19,100] {logging_mixin.py:109} INFO - [2021-08-31 12:52:19,099] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:52:19,115] {logging_mixin.py:109} INFO - [2021-08-31 12:52:19,115] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:52:19,123] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.029 seconds
[2021-08-31 12:52:49,255] {processor.py:162} INFO - Started process (PID=7379) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:52:49,257] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:52:49,258] {logging_mixin.py:109} INFO - [2021-08-31 12:52:49,258] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:52:50,184] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:52:51,125] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:52:51,153] {logging_mixin.py:109} INFO - [2021-08-31 12:52:51,152] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:52:51,173] {logging_mixin.py:109} INFO - [2021-08-31 12:52:51,173] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:52:51,182] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.931 seconds
[2021-08-31 12:53:21,295] {processor.py:162} INFO - Started process (PID=7496) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:53:21,297] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:53:21,297] {logging_mixin.py:109} INFO - [2021-08-31 12:53:21,297] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:53:22,313] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:53:23,355] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:53:23,381] {logging_mixin.py:109} INFO - [2021-08-31 12:53:23,381] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:53:23,399] {logging_mixin.py:109} INFO - [2021-08-31 12:53:23,399] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:53:23,407] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.117 seconds
[2021-08-31 12:53:53,497] {processor.py:162} INFO - Started process (PID=7604) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:53:53,499] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:53:53,500] {logging_mixin.py:109} INFO - [2021-08-31 12:53:53,500] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:53:54,482] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:53:55,412] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:53:55,441] {logging_mixin.py:109} INFO - [2021-08-31 12:53:55,440] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:53:55,462] {logging_mixin.py:109} INFO - [2021-08-31 12:53:55,462] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:53:55,477] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.984 seconds
[2021-08-31 12:54:25,617] {processor.py:162} INFO - Started process (PID=7721) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:54:25,618] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:54:25,619] {logging_mixin.py:109} INFO - [2021-08-31 12:54:25,619] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:54:26,519] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:54:27,277] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:54:27,300] {logging_mixin.py:109} INFO - [2021-08-31 12:54:27,299] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:54:27,316] {logging_mixin.py:109} INFO - [2021-08-31 12:54:27,316] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:54:27,324] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.710 seconds
[2021-08-31 12:54:57,426] {processor.py:162} INFO - Started process (PID=7837) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:54:57,427] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:54:57,428] {logging_mixin.py:109} INFO - [2021-08-31 12:54:57,428] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:54:58,429] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:54:59,330] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:54:59,356] {logging_mixin.py:109} INFO - [2021-08-31 12:54:59,355] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:54:59,375] {logging_mixin.py:109} INFO - [2021-08-31 12:54:59,375] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:54:59,383] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.961 seconds
[2021-08-31 12:55:29,487] {processor.py:162} INFO - Started process (PID=7946) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:55:29,489] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:55:29,489] {logging_mixin.py:109} INFO - [2021-08-31 12:55:29,489] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:55:30,513] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:55:31,434] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:55:31,458] {logging_mixin.py:109} INFO - [2021-08-31 12:55:31,457] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:55:31,481] {logging_mixin.py:109} INFO - [2021-08-31 12:55:31,481] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:55:31,495] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.011 seconds
[2021-08-31 12:56:01,615] {processor.py:162} INFO - Started process (PID=8064) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:56:01,617] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:56:01,617] {logging_mixin.py:109} INFO - [2021-08-31 12:56:01,617] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:56:02,760] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:56:03,804] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:56:03,840] {logging_mixin.py:109} INFO - [2021-08-31 12:56:03,840] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:56:03,876] {logging_mixin.py:109} INFO - [2021-08-31 12:56:03,876] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:56:03,902] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.290 seconds
[2021-08-31 12:56:33,974] {processor.py:162} INFO - Started process (PID=8180) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:56:33,976] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:56:33,977] {logging_mixin.py:109} INFO - [2021-08-31 12:56:33,976] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:56:34,909] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:56:35,731] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:56:35,756] {logging_mixin.py:109} INFO - [2021-08-31 12:56:35,756] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:56:35,778] {logging_mixin.py:109} INFO - [2021-08-31 12:56:35,777] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:56:35,786] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.816 seconds
[2021-08-31 12:57:05,926] {processor.py:162} INFO - Started process (PID=8296) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:57:05,928] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:57:05,929] {logging_mixin.py:109} INFO - [2021-08-31 12:57:05,929] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:57:07,252] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:57:08,205] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:57:08,238] {logging_mixin.py:109} INFO - [2021-08-31 12:57:08,238] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:57:08,258] {logging_mixin.py:109} INFO - [2021-08-31 12:57:08,258] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:57:08,268] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.346 seconds
[2021-08-31 12:57:38,357] {processor.py:162} INFO - Started process (PID=8411) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:57:38,362] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:57:38,364] {logging_mixin.py:109} INFO - [2021-08-31 12:57:38,364] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:57:39,325] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:57:40,194] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:57:40,229] {logging_mixin.py:109} INFO - [2021-08-31 12:57:40,228] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:57:40,249] {logging_mixin.py:109} INFO - [2021-08-31 12:57:40,249] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:57:40,257] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.903 seconds
[2021-08-31 12:58:10,359] {processor.py:162} INFO - Started process (PID=8523) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:58:10,360] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:58:10,361] {logging_mixin.py:109} INFO - [2021-08-31 12:58:10,361] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:58:11,383] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:58:12,220] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:58:12,246] {logging_mixin.py:109} INFO - [2021-08-31 12:58:12,245] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:58:12,265] {logging_mixin.py:109} INFO - [2021-08-31 12:58:12,265] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:58:12,273] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.918 seconds
[2021-08-31 12:58:42,357] {processor.py:162} INFO - Started process (PID=8639) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:58:42,358] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:58:42,359] {logging_mixin.py:109} INFO - [2021-08-31 12:58:42,359] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:58:43,344] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:58:44,199] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:58:44,249] {logging_mixin.py:109} INFO - [2021-08-31 12:58:44,248] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:58:44,275] {logging_mixin.py:109} INFO - [2021-08-31 12:58:44,275] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:58:44,285] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.932 seconds
[2021-08-31 12:59:14,393] {processor.py:162} INFO - Started process (PID=8756) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:59:14,394] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:59:14,395] {logging_mixin.py:109} INFO - [2021-08-31 12:59:14,395] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:59:15,521] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:59:16,389] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:59:16,416] {logging_mixin.py:109} INFO - [2021-08-31 12:59:16,416] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:59:16,437] {logging_mixin.py:109} INFO - [2021-08-31 12:59:16,436] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:59:16,444] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.055 seconds
[2021-08-31 12:59:46,540] {processor.py:162} INFO - Started process (PID=8864) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 12:59:46,540] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 12:59:46,541] {logging_mixin.py:109} INFO - [2021-08-31 12:59:46,541] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:59:47,729] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 12:59:48,697] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 12:59:48,724] {logging_mixin.py:109} INFO - [2021-08-31 12:59:48,723] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 12:59:48,748] {logging_mixin.py:109} INFO - [2021-08-31 12:59:48,748] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 12:59:48,757] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.220 seconds
[2021-08-31 13:00:18,878] {processor.py:162} INFO - Started process (PID=8980) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:00:18,879] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:00:18,880] {logging_mixin.py:109} INFO - [2021-08-31 13:00:18,880] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:00:19,869] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:00:20,667] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:00:20,691] {logging_mixin.py:109} INFO - [2021-08-31 13:00:20,691] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:00:20,711] {logging_mixin.py:109} INFO - [2021-08-31 13:00:20,711] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:00:20,725] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.851 seconds
[2021-08-31 13:00:50,871] {processor.py:162} INFO - Started process (PID=9096) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:00:50,873] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:00:50,874] {logging_mixin.py:109} INFO - [2021-08-31 13:00:50,874] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:00:51,933] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:00:52,801] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:00:52,827] {logging_mixin.py:109} INFO - [2021-08-31 13:00:52,827] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:00:52,846] {logging_mixin.py:109} INFO - [2021-08-31 13:00:52,846] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:00:52,854] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.988 seconds
[2021-08-31 13:01:22,982] {processor.py:162} INFO - Started process (PID=9210) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:01:22,984] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:01:22,985] {logging_mixin.py:109} INFO - [2021-08-31 13:01:22,985] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:01:24,009] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:01:24,896] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:01:24,921] {logging_mixin.py:109} INFO - [2021-08-31 13:01:24,921] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:01:24,943] {logging_mixin.py:109} INFO - [2021-08-31 13:01:24,943] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:01:24,951] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.973 seconds
[2021-08-31 13:01:55,085] {processor.py:162} INFO - Started process (PID=9320) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:01:55,086] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:01:55,086] {logging_mixin.py:109} INFO - [2021-08-31 13:01:55,086] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:01:56,000] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:01:56,891] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:01:56,916] {logging_mixin.py:109} INFO - [2021-08-31 13:01:56,916] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:01:56,935] {logging_mixin.py:109} INFO - [2021-08-31 13:01:56,934] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:01:56,944] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.862 seconds
[2021-08-31 13:02:27,074] {processor.py:162} INFO - Started process (PID=9436) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:02:27,074] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:02:27,075] {logging_mixin.py:109} INFO - [2021-08-31 13:02:27,075] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:02:28,122] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:02:29,001] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:02:29,030] {logging_mixin.py:109} INFO - [2021-08-31 13:02:29,029] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:02:29,054] {logging_mixin.py:109} INFO - [2021-08-31 13:02:29,054] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:02:29,065] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.994 seconds
[2021-08-31 13:02:59,203] {processor.py:162} INFO - Started process (PID=9552) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:02:59,294] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:02:59,295] {logging_mixin.py:109} INFO - [2021-08-31 13:02:59,295] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:03:00,374] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:03:01,310] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:03:01,336] {logging_mixin.py:109} INFO - [2021-08-31 13:03:01,336] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:03:01,354] {logging_mixin.py:109} INFO - [2021-08-31 13:03:01,354] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:03:01,362] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.164 seconds
[2021-08-31 13:03:31,436] {processor.py:162} INFO - Started process (PID=9660) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:03:31,437] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:03:31,438] {logging_mixin.py:109} INFO - [2021-08-31 13:03:31,438] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:03:32,537] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:03:33,483] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:03:33,507] {logging_mixin.py:109} INFO - [2021-08-31 13:03:33,507] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:03:33,526] {logging_mixin.py:109} INFO - [2021-08-31 13:03:33,526] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:03:33,536] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.105 seconds
[2021-08-31 13:04:03,671] {processor.py:162} INFO - Started process (PID=9776) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:04:03,672] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:04:03,673] {logging_mixin.py:109} INFO - [2021-08-31 13:04:03,673] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:04:04,579] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:04:05,462] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:04:05,484] {logging_mixin.py:109} INFO - [2021-08-31 13:04:05,484] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:04:05,501] {logging_mixin.py:109} INFO - [2021-08-31 13:04:05,500] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:04:05,509] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.842 seconds
[2021-08-31 13:04:35,640] {processor.py:162} INFO - Started process (PID=9892) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:04:35,641] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:04:35,642] {logging_mixin.py:109} INFO - [2021-08-31 13:04:35,642] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:04:36,535] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:04:37,388] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:04:37,417] {logging_mixin.py:109} INFO - [2021-08-31 13:04:37,417] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:04:37,440] {logging_mixin.py:109} INFO - [2021-08-31 13:04:37,440] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:04:37,450] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.813 seconds
[2021-08-31 13:05:07,581] {processor.py:162} INFO - Started process (PID=10009) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:05:07,582] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:05:07,583] {logging_mixin.py:109} INFO - [2021-08-31 13:05:07,583] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:05:08,517] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:05:09,395] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:05:09,423] {logging_mixin.py:109} INFO - [2021-08-31 13:05:09,423] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:05:09,442] {logging_mixin.py:109} INFO - [2021-08-31 13:05:09,442] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:05:09,450] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.872 seconds
[2021-08-31 13:05:39,615] {processor.py:162} INFO - Started process (PID=10117) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:05:39,616] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:05:39,616] {logging_mixin.py:109} INFO - [2021-08-31 13:05:39,616] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:05:40,468] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:05:41,465] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:05:41,492] {logging_mixin.py:109} INFO - [2021-08-31 13:05:41,491] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:05:41,511] {logging_mixin.py:109} INFO - [2021-08-31 13:05:41,511] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:05:41,520] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.909 seconds
[2021-08-31 13:06:11,676] {processor.py:162} INFO - Started process (PID=10234) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:06:11,678] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:06:11,679] {logging_mixin.py:109} INFO - [2021-08-31 13:06:11,679] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:06:12,653] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:06:13,546] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:06:13,573] {logging_mixin.py:109} INFO - [2021-08-31 13:06:13,572] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:06:13,595] {logging_mixin.py:109} INFO - [2021-08-31 13:06:13,595] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:06:13,604] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.932 seconds
[2021-08-31 13:06:43,674] {processor.py:162} INFO - Started process (PID=10350) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:06:43,675] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:06:43,676] {logging_mixin.py:109} INFO - [2021-08-31 13:06:43,676] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:06:44,743] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:06:45,645] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:06:45,669] {logging_mixin.py:109} INFO - [2021-08-31 13:06:45,668] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:06:45,690] {logging_mixin.py:109} INFO - [2021-08-31 13:06:45,690] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:06:45,700] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.030 seconds
[2021-08-31 13:07:15,804] {processor.py:162} INFO - Started process (PID=10466) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:07:15,806] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:07:15,807] {logging_mixin.py:109} INFO - [2021-08-31 13:07:15,807] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:07:16,805] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:07:17,640] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:07:17,665] {logging_mixin.py:109} INFO - [2021-08-31 13:07:17,664] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:07:17,680] {logging_mixin.py:109} INFO - [2021-08-31 13:07:17,680] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:07:17,688] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.888 seconds
[2021-08-31 13:07:47,738] {processor.py:162} INFO - Started process (PID=10575) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:07:47,740] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:07:47,740] {logging_mixin.py:109} INFO - [2021-08-31 13:07:47,740] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:07:48,658] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:07:49,493] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:07:49,539] {logging_mixin.py:109} INFO - [2021-08-31 13:07:49,538] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:07:49,558] {logging_mixin.py:109} INFO - [2021-08-31 13:07:49,558] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:07:49,567] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.833 seconds
[2021-08-31 13:08:19,706] {processor.py:162} INFO - Started process (PID=10691) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:08:19,707] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:08:19,707] {logging_mixin.py:109} INFO - [2021-08-31 13:08:19,707] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:08:20,735] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:08:21,689] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:08:21,720] {logging_mixin.py:109} INFO - [2021-08-31 13:08:21,720] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:08:21,744] {logging_mixin.py:109} INFO - [2021-08-31 13:08:21,743] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:08:21,754] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.052 seconds
[2021-08-31 13:08:51,894] {processor.py:162} INFO - Started process (PID=10807) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:08:51,894] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:08:51,895] {logging_mixin.py:109} INFO - [2021-08-31 13:08:51,895] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:08:52,861] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:08:53,792] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:08:53,817] {logging_mixin.py:109} INFO - [2021-08-31 13:08:53,816] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:08:53,839] {logging_mixin.py:109} INFO - [2021-08-31 13:08:53,839] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:08:53,850] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.960 seconds
[2021-08-31 13:09:23,992] {processor.py:162} INFO - Started process (PID=10923) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:09:23,994] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:09:23,994] {logging_mixin.py:109} INFO - [2021-08-31 13:09:23,994] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:09:25,089] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:09:25,887] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:09:25,910] {logging_mixin.py:109} INFO - [2021-08-31 13:09:25,909] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:09:25,931] {logging_mixin.py:109} INFO - [2021-08-31 13:09:25,930] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:09:25,940] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.951 seconds
[2021-08-31 13:09:56,032] {processor.py:162} INFO - Started process (PID=11038) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:09:56,037] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:09:56,039] {logging_mixin.py:109} INFO - [2021-08-31 13:09:56,039] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:09:56,986] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:09:57,876] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:09:57,906] {logging_mixin.py:109} INFO - [2021-08-31 13:09:57,906] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:09:57,932] {logging_mixin.py:109} INFO - [2021-08-31 13:09:57,931] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:09:57,942] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.913 seconds
[2021-08-31 13:10:28,110] {processor.py:162} INFO - Started process (PID=11147) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:10:28,111] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:10:28,112] {logging_mixin.py:109} INFO - [2021-08-31 13:10:28,112] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:10:29,077] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:10:29,922] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:10:29,951] {logging_mixin.py:109} INFO - [2021-08-31 13:10:29,950] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:10:29,972] {logging_mixin.py:109} INFO - [2021-08-31 13:10:29,972] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:10:30,022] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.915 seconds
[2021-08-31 13:11:00,160] {processor.py:162} INFO - Started process (PID=11264) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:11:00,162] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:11:00,163] {logging_mixin.py:109} INFO - [2021-08-31 13:11:00,162] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:11:01,360] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:11:02,264] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:11:02,288] {logging_mixin.py:109} INFO - [2021-08-31 13:11:02,288] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:11:02,306] {logging_mixin.py:109} INFO - [2021-08-31 13:11:02,306] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:11:02,315] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.158 seconds
[2021-08-31 13:11:32,423] {processor.py:162} INFO - Started process (PID=11417) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:11:32,424] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:11:32,425] {logging_mixin.py:109} INFO - [2021-08-31 13:11:32,425] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:11:33,293] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:11:34,204] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:11:34,231] {logging_mixin.py:109} INFO - [2021-08-31 13:11:34,230] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:11:34,254] {logging_mixin.py:109} INFO - [2021-08-31 13:11:34,254] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:11:34,270] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.850 seconds
[2021-08-31 13:12:04,310] {processor.py:162} INFO - Started process (PID=11579) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:12:04,311] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:12:04,312] {logging_mixin.py:109} INFO - [2021-08-31 13:12:04,312] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:12:05,171] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:12:05,910] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:12:05,933] {logging_mixin.py:109} INFO - [2021-08-31 13:12:05,932] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:12:05,949] {logging_mixin.py:109} INFO - [2021-08-31 13:12:05,948] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:12:05,956] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.651 seconds
[2021-08-31 13:12:36,065] {processor.py:162} INFO - Started process (PID=11696) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:12:36,068] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:12:36,069] {logging_mixin.py:109} INFO - [2021-08-31 13:12:36,069] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:12:36,944] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:12:37,772] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:12:37,796] {logging_mixin.py:109} INFO - [2021-08-31 13:12:37,795] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:12:37,817] {logging_mixin.py:109} INFO - [2021-08-31 13:12:37,817] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:12:37,831] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.770 seconds
[2021-08-31 13:13:08,336] {processor.py:162} INFO - Started process (PID=11813) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:13:08,338] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:13:08,339] {logging_mixin.py:109} INFO - [2021-08-31 13:13:08,339] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:13:09,422] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:13:10,301] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:13:10,329] {logging_mixin.py:109} INFO - [2021-08-31 13:13:10,328] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:13:10,352] {logging_mixin.py:109} INFO - [2021-08-31 13:13:10,352] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:13:10,364] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.031 seconds
[2021-08-31 13:13:40,465] {processor.py:162} INFO - Started process (PID=11921) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:13:40,467] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:13:40,467] {logging_mixin.py:109} INFO - [2021-08-31 13:13:40,467] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:13:41,356] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:13:42,255] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:13:42,285] {logging_mixin.py:109} INFO - [2021-08-31 13:13:42,284] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:13:42,308] {logging_mixin.py:109} INFO - [2021-08-31 13:13:42,307] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:13:42,321] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.860 seconds
[2021-08-31 13:14:12,411] {processor.py:162} INFO - Started process (PID=12037) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:14:12,413] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:14:12,413] {logging_mixin.py:109} INFO - [2021-08-31 13:14:12,413] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:14:13,190] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:14:13,963] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:14:13,986] {logging_mixin.py:109} INFO - [2021-08-31 13:14:13,985] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:14:14,002] {logging_mixin.py:109} INFO - [2021-08-31 13:14:14,002] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:14:14,010] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.603 seconds
[2021-08-31 13:14:44,682] {processor.py:162} INFO - Started process (PID=12154) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:14:44,683] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:14:44,684] {logging_mixin.py:109} INFO - [2021-08-31 13:14:44,684] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:14:45,587] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:14:46,497] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:14:46,523] {logging_mixin.py:109} INFO - [2021-08-31 13:14:46,523] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:14:46,546] {logging_mixin.py:109} INFO - [2021-08-31 13:14:46,545] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:14:46,559] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.880 seconds
[2021-08-31 13:15:16,704] {processor.py:162} INFO - Started process (PID=12270) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:15:16,706] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:15:16,706] {logging_mixin.py:109} INFO - [2021-08-31 13:15:16,706] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:15:17,583] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:15:18,482] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:15:18,507] {logging_mixin.py:109} INFO - [2021-08-31 13:15:18,506] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:15:18,525] {logging_mixin.py:109} INFO - [2021-08-31 13:15:18,525] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:15:18,533] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.832 seconds
[2021-08-31 13:15:48,953] {processor.py:162} INFO - Started process (PID=12378) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:15:48,954] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:15:48,955] {logging_mixin.py:109} INFO - [2021-08-31 13:15:48,955] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:15:49,808] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:15:50,633] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:15:50,661] {logging_mixin.py:109} INFO - [2021-08-31 13:15:50,660] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:15:50,689] {logging_mixin.py:109} INFO - [2021-08-31 13:15:50,689] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:15:50,700] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.751 seconds
[2021-08-31 13:16:20,782] {processor.py:162} INFO - Started process (PID=12494) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:16:20,783] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:16:20,784] {logging_mixin.py:109} INFO - [2021-08-31 13:16:20,784] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:16:21,587] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:16:22,602] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:16:22,626] {logging_mixin.py:109} INFO - [2021-08-31 13:16:22,626] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:16:22,647] {logging_mixin.py:109} INFO - [2021-08-31 13:16:22,647] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:16:22,661] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.883 seconds
[2021-08-31 13:16:52,793] {processor.py:162} INFO - Started process (PID=12611) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:16:52,794] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:16:52,795] {logging_mixin.py:109} INFO - [2021-08-31 13:16:52,795] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:16:53,627] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:16:54,721] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:16:54,749] {logging_mixin.py:109} INFO - [2021-08-31 13:16:54,749] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:16:54,774] {logging_mixin.py:109} INFO - [2021-08-31 13:16:54,774] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:16:54,790] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.001 seconds
[2021-08-31 13:17:24,899] {processor.py:162} INFO - Started process (PID=12720) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:17:24,900] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:17:24,900] {logging_mixin.py:109} INFO - [2021-08-31 13:17:24,900] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:17:25,706] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:17:26,693] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:17:26,718] {logging_mixin.py:109} INFO - [2021-08-31 13:17:26,718] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:17:26,741] {logging_mixin.py:109} INFO - [2021-08-31 13:17:26,740] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:17:26,753] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.858 seconds
[2021-08-31 13:17:56,867] {processor.py:162} INFO - Started process (PID=12929) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:17:56,869] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:17:56,870] {logging_mixin.py:109} INFO - [2021-08-31 13:17:56,870] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:17:57,867] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:17:58,791] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:17:58,813] {logging_mixin.py:109} INFO - [2021-08-31 13:17:58,812] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:17:58,829] {logging_mixin.py:109} INFO - [2021-08-31 13:17:58,829] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:17:58,841] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.979 seconds
[2021-08-31 13:18:28,889] {processor.py:162} INFO - Started process (PID=13091) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:18:28,891] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:18:28,892] {logging_mixin.py:109} INFO - [2021-08-31 13:18:28,892] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:18:29,839] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:18:30,777] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:18:30,808] {logging_mixin.py:109} INFO - [2021-08-31 13:18:30,808] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:18:30,829] {logging_mixin.py:109} INFO - [2021-08-31 13:18:30,829] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:18:30,838] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.953 seconds
[2021-08-31 13:19:01,241] {processor.py:162} INFO - Started process (PID=13208) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:19:01,243] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:19:01,244] {logging_mixin.py:109} INFO - [2021-08-31 13:19:01,243] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:19:02,235] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:19:03,149] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:19:03,177] {logging_mixin.py:109} INFO - [2021-08-31 13:19:03,177] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:19:03,201] {logging_mixin.py:109} INFO - [2021-08-31 13:19:03,200] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:19:03,210] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.973 seconds
[2021-08-31 13:19:33,333] {processor.py:162} INFO - Started process (PID=13316) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:19:33,334] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:19:33,335] {logging_mixin.py:109} INFO - [2021-08-31 13:19:33,334] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:19:34,152] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:19:34,975] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:19:35,006] {logging_mixin.py:109} INFO - [2021-08-31 13:19:35,005] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:19:35,031] {logging_mixin.py:109} INFO - [2021-08-31 13:19:35,031] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:19:35,046] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.717 seconds
[2021-08-31 13:20:05,160] {processor.py:162} INFO - Started process (PID=13524) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:20:05,161] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:20:05,161] {logging_mixin.py:109} INFO - [2021-08-31 13:20:05,161] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:20:06,235] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:20:07,306] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:20:07,335] {logging_mixin.py:109} INFO - [2021-08-31 13:20:07,334] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:20:07,353] {logging_mixin.py:109} INFO - [2021-08-31 13:20:07,353] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:20:07,368] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 2.213 seconds
[2021-08-31 13:20:37,544] {processor.py:162} INFO - Started process (PID=13687) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:20:37,546] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:20:37,548] {logging_mixin.py:109} INFO - [2021-08-31 13:20:37,548] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:20:38,372] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:20:39,241] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:20:39,262] {logging_mixin.py:109} INFO - [2021-08-31 13:20:39,261] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:20:39,283] {logging_mixin.py:109} INFO - [2021-08-31 13:20:39,283] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:20:39,298] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.758 seconds
[2021-08-31 13:21:09,416] {processor.py:162} INFO - Started process (PID=13797) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:21:09,417] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:21:09,418] {logging_mixin.py:109} INFO - [2021-08-31 13:21:09,418] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:21:10,253] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:21:11,203] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:21:11,239] {logging_mixin.py:109} INFO - [2021-08-31 13:21:11,239] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:21:11,268] {logging_mixin.py:109} INFO - [2021-08-31 13:21:11,268] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:21:11,282] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.870 seconds
[2021-08-31 13:21:41,633] {processor.py:162} INFO - Started process (PID=13915) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:21:41,634] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:21:41,634] {logging_mixin.py:109} INFO - [2021-08-31 13:21:41,634] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:21:42,429] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:21:43,247] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:21:43,273] {logging_mixin.py:109} INFO - [2021-08-31 13:21:43,272] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:21:43,290] {logging_mixin.py:109} INFO - [2021-08-31 13:21:43,290] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:21:43,298] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.668 seconds
[2021-08-31 13:22:13,406] {processor.py:162} INFO - Started process (PID=14077) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:22:13,407] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:22:13,408] {logging_mixin.py:109} INFO - [2021-08-31 13:22:13,408] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:22:14,224] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:22:15,044] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:22:15,072] {logging_mixin.py:109} INFO - [2021-08-31 13:22:15,072] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:22:15,095] {logging_mixin.py:109} INFO - [2021-08-31 13:22:15,095] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:22:15,103] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.701 seconds
[2021-08-31 13:22:45,199] {processor.py:162} INFO - Started process (PID=14185) to work on /opt/airflow/dags/snowflake2.py
[2021-08-31 13:22:45,201] {processor.py:613} INFO - Processing file /opt/airflow/dags/snowflake2.py for tasks to queue
[2021-08-31 13:22:45,202] {logging_mixin.py:109} INFO - [2021-08-31 13:22:45,201] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:22:46,017] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:94 UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-08-31 13:22:46,905] {processor.py:623} INFO - DAG(s) dict_keys(['covid_data_s3_to_snowflake']) retrieved from /opt/airflow/dags/snowflake2.py
[2021-08-31 13:22:46,933] {logging_mixin.py:109} INFO - [2021-08-31 13:22:46,933] {dag.py:1833} INFO - Sync 1 DAGs
[2021-08-31 13:22:46,957] {logging_mixin.py:109} INFO - [2021-08-31 13:22:46,957] {dag.py:2306} INFO - Setting next_dagrun for covid_data_s3_to_snowflake to 2021-08-30 00:00:00+00:00
[2021-08-31 13:22:46,972] {processor.py:170} INFO - Processing /opt/airflow/dags/snowflake2.py took 1.777 seconds
